### ISSUE TITLE
Error running install.py for extension

### ISSUE THREAD

**Issue by fgtm2023** [SpenserCai/sd-webui-deoldify#1]
Peace, thanks a lot for this great extension, i was waiting to use deoldify with AUTOMATIC111, i got this two error messages when installing the extension, then after the extension installed, i chose deoldify in Extras tab and set image size scale by 1 and clicked generate, i got a new error message. 

i am using AMD RX vega 56 GPU in Ubuntu Linux ,  
• AUTOMATIC1111 v1.5.1
• python: 3.10.12
• torch: 2.1.0.dev20230711+rocm5.5  
• gradio: 3.32.0

*** Error running install.py for extension /home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify.
*** Command: "/usr/local/bin/python" "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/install.py"
*** Error code: 1
*** stderr: 
*** Downloading:   0%|          | 0.00/834M [00:00<?, ?B/s]

Traceback (most recent call last):
***   File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/install.py", line 43, in <module>
***     download(video_model_url, video_model_path)
***   File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/install.py", line 33, in download
***     urllib.request.urlretrieve(url, path, reporthook=lambda count, block_size, total_size: progress.update(block_size))
***   File "/usr/lib/python3.10/urllib/request.py", line 280, in urlretrieve
***     raise ContentTooShortError(
*** urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 873520337 out of 874066230 bytes>

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

last error message: 

Starting job None
Starting job extras
Downloading: "https://download.pytorch.org/models/resnet101-63fe2227.pth" to /home/abdo/.cache/torch/hub/checkpoints/resnet101-63fe2227.pth
 98%|█████████████████████████████████████████████████████████████████████████████▌ | 167M/171M [01:26<00:01, 2.03MB/s]
*** Error completing request
*** Arguments: (0, <PIL.Image.Image image mode=RGB size=355x746 at 0x7F18443413C0>, None, '', '', True, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, True, 35, False) {}
    Traceback (most recent call last):
      File "/home/abdo/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/home/abdo/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/home/abdo/stable-diffusion-webui/modules/postprocessing.py", line 62, in run_postprocessing
        scripts.scripts_postproc.run(pp, args)
      File "/home/abdo/stable-diffusion-webui/modules/scripts_postprocessing.py", line 130, in run
        script.process(pp, **process_args)
      File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/scripts/postprocessing_deoldify.py", line 54, in process
        pp.image = self.process_image(pp.image, render_factor, artistic)
      File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/scripts/postprocessing_deoldify.py", line 46, in process_image
        vis = get_image_colorizer(root_folder=Path("models"),render_factor=render_factor, artistic=artistic)
      File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/deoldify/visualize.py", line 416, in get_image_colorizer
        return get_stable_image_colorizer(root_folder=root_folder, render_factor=render_factor)
      File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/deoldify/visualize.py", line 425, in get_stable_image_colorizer
        learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
      File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/deoldify/generators.py", line 15, in gen_inference_wide
        learn = gen_learner_wide(
      File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/deoldify/generators.py", line 27, in gen_learner_wide
        return unet_learner_wide(
      File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/deoldify/generators.py", line 58, in unet_learner_wide
        body = create_body(arch, pretrained)
      File "/home/abdo/stable-diffusion-webui/extensions/sd-webui-deoldify/fastai/vision/learner.py", line 56, in create_body
        model = arch(pretrained=pretrained)
      File "/home/abdo/.local/lib/python3.10/site-packages/torchvision/models/_utils.py", line 142, in wrapper
        return fn(*args, **kwargs)
      File "/home/abdo/.local/lib/python3.10/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
        return builder(*args, **kwargs)
      File "/home/abdo/.local/lib/python3.10/site-packages/torchvision/models/resnet.py", line 795, in resnet101
        return _resnet(Bottleneck, [3, 4, 23, 3], weights, progress, **kwargs)
      File "/home/abdo/.local/lib/python3.10/site-packages/torchvision/models/resnet.py", line 301, in _resnet
        model.load_state_dict(weights.get_state_dict(progress=progress, check_hash=True))
      File "/home/abdo/.local/lib/python3.10/site-packages/torchvision/models/_api.py", line 90, in get_state_dict
        return load_state_dict_from_url(self.url, *args, **kwargs)
      File "/home/abdo/.local/lib/python3.10/site-packages/torch/hub.py", line 757, in load_state_dict_from_url
        download_url_to_file(url, cached_file, hash_prefix, progress=progress)
      File "/home/abdo/.local/lib/python3.10/site-packages/torch/hub.py", line 653, in download_url_to_file
        raise RuntimeError('invalid hash value (expected "{}", got "{}")'
    RuntimeError: invalid hash value (expected "63fe2227", got "377312f2c100f81e73b6e0a23ee17ef093e4f247490ffa79983bd19b1fafef66")

**Comment by fgtm2023** [comment]
i clothed the vpn and tried to generate again and the .pth model downloaded successfully via terminal log, and colored image generated successfully .

**Comment by SpenserCai** [comment]
恭喜你！大部分情况都是网络问题
Congratulations！Most of the time, it's a network problem
