### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kuyin** [SpenserCai/sd-webui-deoldify#3]
*** Error verifying pickled file from I:\GitHub\stable-diffusion-webui\models\deoldify\tmpftyualnn
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "I:\GitHub\stable-diffusion-webui\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "I:\GitHub\stable-diffusion-webui\modules\safe.py", line 95, in check_pt
        unpickler.load()
      File "C:\Users\wyj35\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "C:\Users\wyj35\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1529, in load_global
        klass = self.find_class(module, name)
      File "I:\GitHub\stable-diffusion-webui\modules\safe.py", line 64, in find_class
        raise Exception(f"global '{module}/{name}' is forbidden")
    Exception: global 'functools/partial' is forbidden

---
*** Error completing request
*** Arguments: (0, <PIL.Image.Image image mode=RGB size=800x535 at 0x1A0F98D2DA0>, None, '', '', True, 0, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, False, False, 8, False, 1, False, 0, True, 35, True) {}
    Traceback (most recent call last):
      File "I:\GitHub\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "I:\GitHub\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "I:\GitHub\stable-diffusion-webui\modules\postprocessing.py", line 62, in run_postprocessing
        scripts.scripts_postproc.run(pp, args)
      File "I:\GitHub\stable-diffusion-webui\modules\scripts_postprocessing.py", line 130, in run
        script.process(pp, **process_args)
      File "I:\GitHub\stable-diffusion-webui\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 54, in process
        pp.image = self.process_image(pp.image, render_factor, artistic)
      File "I:\GitHub\stable-diffusion-webui\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 46, in process_image
        vis = get_image_colorizer(root_folder=Path(paths_internal.models_path),render_factor=render_factor, artistic=artistic)
      File "I:\GitHub\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 414, in get_image_colorizer
        return get_artistic_image_colorizer(root_folder=root_folder, render_factor=render_factor)
      File "I:\GitHub\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 437, in get_artistic_image_colorizer
        learn = gen_inference_deep(root_folder=root_folder, weights_name=weights_name)
      File "I:\GitHub\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\generators.py", line 92, in gen_inference_deep
        learn.load(weights_name)
      File "I:\GitHub\stable-diffusion-webui\extensions\sd-webui-deoldify\fastai\basic_train.py", line 267, in load
        if purge: self.purge(clear_opt=ifnone(with_opt, False))
      File "I:\GitHub\stable-diffusion-webui\extensions\sd-webui-deoldify\fastai\basic_train.py", line 325, in purge
        for a in attrs_pkl: setattr(self, a, state[a])
    TypeError: 'NoneType' object is not subscriptable

---

**Comment by SpenserCai** [comment]
you need add --disable-safe-unpickle in sd-webui start command,because deoldify will create a temp file in model dir
