### ISSUE TITLE
UserWarning: Your training set is empty and FileNotFoundError: [WinError 2] for video

### ISSUE THREAD

**Issue by mehmeow12** [SpenserCai/sd-webui-deoldify#30]
Hi, I am trying to run DeOldlify for video without success. DeOldify works for single image without any issues. I have ffmpeg and I updated PATH.

```
g:\Ai\Soft\sd.webui\webui\extensions\sd-webui-deoldify\fastai\data_block.py:451: UserWarning: Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.
  warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
g:\Ai\Soft\sd.webui\webui\extensions\sd-webui-deoldify\fastai\data_block.py:453: UserWarning: Your validation set is empty. If this is by design, use `split_none()`
                 or pass `ignore_empty=True` when labelling to remove this warning.
  warn("""Your validation set is empty. If this is by design, use `split_none()`
g:\Ai\Soft\sd.webui\system\python\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
g:\Ai\Soft\sd.webui\system\python\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Errror while extracting raw frames from source video.  Details: [WinError 2] system cannot find the specified file
Traceback (most recent call last):
  File "g:\Ai\Soft\sd.webui\webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 251, in _extract_raw_frames
    process.run()
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] system cannot find the specified file
Traceback (most recent call last):
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "g:\Ai\Soft\sd.webui\webui\extensions\sd-webui-deoldify\scripts\ui_deoldify.py", line 28, in process_image
    out_video = colorizer.colorize_from_file_name(video_name, render_factor=render_factor,g_process_bar=process)
  File "g:\Ai\Soft\sd.webui\webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 372, in colorize_from_file_name
    return self._colorize_from_path(
  File "g:\Ai\Soft\sd.webui\webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 384, in _colorize_from_path
    self._extract_raw_frames(source_path)
  File "g:\Ai\Soft\sd.webui\webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 259, in _extract_raw_frames
    raise e
  File "g:\Ai\Soft\sd.webui\webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 251, in _extract_raw_frames
    process.run()
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "g:\Ai\Soft\sd.webui\system\python\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] system cannot find the specified file
```

**Comment by SpenserCai** [comment]
From the error message, it does seem to be an issue with ffmpeg. In fact, I just helped another user solve the same problem. If you are using conda, please install ffmpeg in your conda environment. You can refer to this link for instructions: https://anaconda.org/conda-forge/ffmpeg.

**Comment by mehmeow12** [comment]
I was using conda for different project. I install ffmpeg via provided link and it didnt helped :(

**Comment by SpenserCai** [comment]
same [issue](https://github.com/SpenserCai/sd-webui-deoldify/issues/32)
