### ISSUE TITLE
win10从秋叶sd扩展安装后报错，fastprogress

### ISSUE THREAD

**Issue by haonanrenjiushiwo** [SpenserCai/sd-webui-deoldify#40]
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
2023-10-11 15:14:20,090 - ControlNet - INFO - ControlNet v1.1.410
*** Error loading script: api.py
    Traceback (most recent call last):
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\scripts\api.py", line 15, in <module>
        from scripts.deoldify_base import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\scripts\deoldify_base.py", line 23, in <module>
        from deoldify.visualize import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\deoldify\visualize.py", line 1, in <module>
        from fastai.core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\core.py", line 2, in <module>
        from .imports.core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\imports\__init__.py", line 1, in <module>
        from .core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\imports\core.py", line 24, in <module>
        from fastprogress.fastprogress import MasterBar, ProgressBar
    ModuleNotFoundError: No module named 'fastprogress'

---
*** Error loading script: deoldify_base.py
    Traceback (most recent call last):
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\scripts\deoldify_base.py", line 23, in <module>
        from deoldify.visualize import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\deoldify\visualize.py", line 1, in <module>
        from fastai.core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\core.py", line 2, in <module>
        from .imports.core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\imports\__init__.py", line 1, in <module>
        from .core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\imports\core.py", line 24, in <module>
        from fastprogress.fastprogress import MasterBar, ProgressBar
    ModuleNotFoundError: No module named 'fastprogress'

---
*** Error loading script: postprocessing_deoldify.py
    Traceback (most recent call last):
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 12, in <module>
        from scripts.deoldify_base import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\scripts\deoldify_base.py", line 23, in <module>
        from deoldify.visualize import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\deoldify\visualize.py", line 1, in <module>
        from fastai.core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\core.py", line 2, in <module>
        from .imports.core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\imports\__init__.py", line 1, in <module>
        from .core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\imports\core.py", line 24, in <module>
        from fastprogress.fastprogress import MasterBar, ProgressBar
    ModuleNotFoundError: No module named 'fastprogress'

---
*** Error loading script: ui_deoldify.py
    Traceback (most recent call last):
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\scripts\ui_deoldify.py", line 10, in <module>
        from scripts.deoldify_base import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\scripts\deoldify_base.py", line 23, in <module>
        from deoldify.visualize import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\deoldify\visualize.py", line 1, in <module>
        from fastai.core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\core.py", line 2, in <module>
        from .imports.core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\imports\__init__.py", line 1, in <module>
        from .core import *
      File "F:\draw\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-deoldify\fastai\imports\core.py", line 24, in <module>
        from fastprogress.fastprogress import MasterBar, ProgressBar
    ModuleNotFoundError: No module named 'fastprogress'

**Comment by SpenserCai** [comment]
检查网络插件自动安装依赖的过程中出问题了（网络不稳定）

**Comment by haonanrenjiushiwo** [comment]
3q




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SpenserCai/sd-webui-deoldify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SpenserCai/sd-webui-deoldify] win10从秋叶sd扩展安装后报错，fastprogress (Issue #40)





 
Closed #40 as completed.
