### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by skytsui** [SpenserCai/sd-webui-deoldify#42]
Unable to run, Already added: 
`--disable-safe-unpickle`

INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
*** Error verifying pickled file from D:\Stable-Diffusion\SD-WebUI-Aki\models\deoldify\tmp6oy4qnaw
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
*** 
    Traceback (most recent call last):
      File "D:\Stable-Diffusion\SD-WebUI-Aki\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "D:\Stable-Diffusion\SD-WebUI-Aki\modules\safe.py", line 95, in check_pt
        unpickler.load()
      File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\pickle.py", line 1529, in load_global
        klass = self.find_class(module, name)
      File "D:\Stable-Diffusion\SD-WebUI-Aki\modules\safe.py", line 64, in find_class
        raise Exception(f"global '{module}/{name}' is forbidden")
    Exception: global 'functools/partial' is forbidden
---
Traceback (most recent call last):
  File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Stable-Diffusion\SD-WebUI-Aki\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Stable-Diffusion\SD-WebUI-Aki\extensions\sd-webui-deoldify\scripts\ui_deoldify.py", line 20, in process_image
    colorizer = get_stable_video_colorizer(root_folder=Path(paths_internal.models_path) ,workfolder=wkfolder)
  File "D:\Stable-Diffusion\SD-WebUI-Aki\extensions\sd-webui-deoldify\deoldify\visualize.py", line 414, in get_stable_video_colorizer
    learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
  File "D:\Stable-Diffusion\SD-WebUI-Aki\extensions\sd-webui-deoldify\deoldify\generators.py", line 19, in gen_inference_wide
    learn.load(weights_name)
  File "D:\Stable-Diffusion\SD-WebUI-Aki\extensions\sd-webui-deoldify\fastai\basic_train.py", line 267, in load
    if purge: self.purge(clear_opt=ifnone(with_opt, False))
  File "D:\Stable-Diffusion\SD-WebUI-Aki\extensions\sd-webui-deoldify\fastai\basic_train.py", line 325, in purge
    for a in attrs_pkl: setattr(self, a, state[a])
TypeError: 'NoneType' object is not subscriptable

**Comment by SpenserCai** [comment]
but warning say:*** You can skip this check with --disable-safe-unpickle commandline argument.

**Comment by Mindscry** [comment]
> but warning say:*** You can skip this check with --disable-safe-unpickle commandline argument.

That doesn't seem like a good solution. That seems like not wearing my seatbelt in the car because it makes my neck itch.
