### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by praxis-alpha** [SpenserCai/sd-webui-deoldify#43]
*** Arguments: (0, <PIL.Image.Image image mode=RGB size=1219x775 at 0x7F23112F0AD0>, None, '', '', True, 0, 4, 512, 512, True, 'None', 'None', 0, 0, 0, 0, True, 35, False, False) {}
    Traceback (most recent call last):
      File "/home/user/.local/share/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/.local/share/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/.local/share/stable-diffusion-webui/modules/postprocessing.py", line 59, in run_postprocessing
        scripts.scripts_postproc.run(pp, args)
      File "/home/user/.local/share/stable-diffusion-webui/modules/scripts_postprocessing.py", line 130, in run
        script.process(pp, **process_args)
      File "/home/user/.local/share/stable-diffusion-webui/extensions/sd-webui-deoldify/scripts/postprocessing_deoldify.py", line 49, in process
        pp.image = self.process_image(pp.image, render_factor, artistic, pre_decolorization)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/.local/share/stable-diffusion-webui/extensions/sd-webui-deoldify/scripts/postprocessing_deoldify.py", line 41, in process_image
        vis = get_image_colorizer(root_folder=Path(paths_internal.models_path),render_factor=render_factor, artistic=artistic)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/.local/share/stable-diffusion-webui/extensions/sd-webui-deoldify/deoldify/visualize.py", line 426, in get_image_colorizer
        return get_stable_image_colorizer(root_folder=root_folder, render_factor=render_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/.local/share/stable-diffusion-webui/extensions/sd-webui-deoldify/deoldify/visualize.py", line 435, in get_stable_image_colorizer
        learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/.local/share/stable-diffusion-webui/extensions/sd-webui-deoldify/deoldify/generators.py", line 19, in gen_inference_wide
        learn.load(weights_name)
      File "/home/user/.local/share/stable-diffusion-webui/extensions/sd-webui-deoldify/fastai/basic_train.py", line 267, in load
        if purge: self.purge(clear_opt=ifnone(with_opt, False))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/.local/share/stable-diffusion-webui/extensions/sd-webui-deoldify/fastai/basic_train.py", line 325, in purge
        for a in attrs_pkl: setattr(self, a, state[a])

    TypeError: 'NoneType' object is not subscriptable

This error is received when attempting to use the DeOldify selection in images.

**Comment by Davikar** [comment]
Yeah, I can't do anything, I just get this error. No special settings. Latest version of A1111 (1.7.0 RC).

**Comment by russianspy1234** [comment]
Same error here.  I added the command line arg like it says to do in
https://github.com/SpenserCai/sd-webui-deoldify/issues/37
but I still get the same error.

**Comment by gma-toronto** [comment]
So i guess this extension is not supported anymore?

**Comment by russianspy1234** [comment]
Managed to fix it by deleting the files and restarting. The first start after installation will take a while, it downloads over a gig with no visual indicator

**Comment by gma-toronto** [comment]
> Managed to fix it by deleting the files and restarting. The first start after installation will take a while, it downloads over a gig with no visual indicator

THe files were there but it dint like them in the "\stable-diffusion-webui\models\deoldify" folder I had to put them in the "\stable-diffusion-webui\extensions\sd-webui-deoldify\models\deoldify" folder and it worked.

**Comment by johnwickstyle** [comment]
hello , you have to download .pth files from [](https://huggingface.co/spensercai/DeOldify/tree/main)   here.
put all 3 files starting from name "colorize" and place into >Stable Diffusion WebUI\extensions\sd-webui-deoldify\models\deoldify\

and you are good to go.

**Comment by johnwickstyle** [comment]
> hello , you have to download 3 .pth files from
> 
> https://huggingface.co/spensercai/DeOldify/tree/main
> 
> put all 3 files into
> 
> > Stable Diffusion WebUI\extensions\sd-webui-deoldify\models\deoldify\
> 
> and you are good to go.

@praxis-alpha @Davikar @russianspy1234 @gma-toronto
