### ISSUE TITLE
CMD spamming HTTP Request

### ISSUE THREAD

**Issue by Blaast** [SpenserCai/sd-webui-deoldify#44]
Hi, I've finally found this extension provokes a "spamming" in my cmd interface (and doesn't work), I have no idea why, and don't know enough to know where to look as for why.
Main issue with this extension activated is this spam :

> HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
> HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"

Also this :

> INFO:modules.shared_state:Ending job Deoldify (1.16 seconds)
> Ending job Deoldify (1.16 seconds)
> 

Some errors I've found in the cmd that feels like they are relevant :

> *** Error verifying pickled file from S:\AI\StableDiffusion-Git\models\deoldify\tmplga18j59
> *** The file may be malicious, so the program is not going to read it.
> *** You can skip this check with --disable-safe-unpickle commandline argument.
> ***
>     Traceback (most recent call last):
>       File "S:\AI\StableDiffusion-Git\modules\safe.py", line 137, in load_with_extra
>         check_pt(filename, extra_handler)
>       File "S:\AI\StableDiffusion-Git\modules\safe.py", line 95, in check_pt
>         unpickler.load()
>       File "S:\AI\StableDiffusion-Git\modules\safe.py", line 64, in find_class
>         raise Exception(f"global '{module}/{name}' is forbidden")
>     Exception: global 'functools/partial' is forbidden
> 
> ---
> *** Error completing request
> *** Arguments: (0, <PIL.Image.Image image mode=RGB size=1488x1984 at 0x24C97C0A8F0>, None, '', '', True, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, 'isnet-general-use', False, False, 240, 10, 10, True, 35, False) {}
>     Traceback (most recent call last):
>       File "S:\AI\StableDiffusion-Git\modules\call_queue.py", line 57, in f
>         res = list(func(*args, **kwargs))
>       File "S:\AI\StableDiffusion-Git\modules\call_queue.py", line 36, in f
>         res = func(*args, **kwargs)
>       File "S:\AI\StableDiffusion-Git\modules\postprocessing.py", line 59, in run_postprocessing
>         scripts.scripts_postproc.run(pp, args)
>       File "S:\AI\StableDiffusion-Git\modules\scripts_postprocessing.py", line 130, in run
>         script.process(pp, **process_args)
>       File "S:\AI\StableDiffusion-Git\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 44, in process
>         pp.image = self.process_image(pp.image, render_factor, artistic)
>       File "S:\AI\StableDiffusion-Git\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 36, in process_image
>         vis = get_image_colorizer(root_folder=Path(paths_internal.models_path),render_factor=render_factor, artistic=artistic)
>       File "S:\AI\StableDiffusion-Git\extensions\sd-webui-deoldify\deoldify\visualize.py", line 426, in get_image_colorizer
>         return get_stable_image_colorizer(root_folder=root_folder, render_factor=render_factor)
>       File "S:\AI\StableDiffusion-Git\extensions\sd-webui-deoldify\deoldify\visualize.py", line 435, in get_stable_image_colorizer
>         learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
>       File "S:\AI\StableDiffusion-Git\extensions\sd-webui-deoldify\deoldify\generators.py", line 19, in gen_inference_wide
>         learn.load(weights_name)
>       File "S:\AI\StableDiffusion-Git\extensions\sd-webui-deoldify\fastai\basic_train.py", line 267, in load
>         if purge: self.purge(clear_opt=ifnone(with_opt, False))
>       File "S:\AI\StableDiffusion-Git\extensions\sd-webui-deoldify\fastai\basic_train.py", line 325, in purge
>         for a in attrs_pkl: setattr(self, a, state[a])
>     TypeError: 'NoneType' object is not subscriptable
> 
> ---

OS : W10 x64
64GB Ram
GTX 1080

If you need anything else, please do ask
And if anyone could help me fix this error, that'd be awesome !
Thanks :)

**Comment by Blaast** [comment]
I've just noticed I didn't update my extensions, I'm trying again

**Comment by SpenserCai** [comment]
Generally speaking, not

**Comment by Giroyoda** [comment]
> Generally speaking, not
Hi
Why does this warning appear at all?
