### ISSUE TITLE
errors out in webui

### ISSUE THREAD

**Issue by 2blackbar** [SpenserCai/sd-webui-deoldify#5]
i added  --disable-safe-unpickle  to solve this but its unsafe 

Starting job None
Starting job extras
*** Error verifying pickled file from F:\sd\models\deoldify\tmp_j255ppt
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "F:\sd\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "F:\sd\modules\safe.py", line 95, in check_pt
        unpickler.load()
      File "C:\Users\BAZO\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "C:\Users\BAZO\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1529, in load_global
        klass = self.find_class(module, name)
      File "F:\sd\modules\safe.py", line 64, in find_class
        raise Exception(f"global '{module}/{name}' is forbidden")
    Exception: global 'functools/partial' is forbidden

---
*** Error completing request
*** Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x1E85EC07AC0>, None, '', '', True, 0, 4, 512, 512, True, 'None', 'None', 0, 0, 0, 0, False, False, 4, 'None', False, False, 240, 10, 10, False, False, 8, 'Nearest Neighbor', False, 1, False, 0, True, 35, False) {}
    Traceback (most recent call last):
      File "F:\sd\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "F:\sd\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "F:\sd\modules\postprocessing.py", line 62, in run_postprocessing
        scripts.scripts_postproc.run(pp, args)
      File "F:\sd\modules\scripts_postprocessing.py", line 130, in run
        script.process(pp, **process_args)
      File "F:\sd\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 54, in process
        pp.image = self.process_image(pp.image, render_factor, artistic)
      File "F:\sd\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 46, in process_image
        vis = get_image_colorizer(root_folder=Path(paths_internal.models_path),render_factor=render_factor, artistic=artistic)
      File "F:\sd\extensions\sd-webui-deoldify\deoldify\visualize.py", line 416, in get_image_colorizer
        return get_stable_image_colorizer(root_folder=root_folder, render_factor=render_factor)
      File "F:\sd\extensions\sd-webui-deoldify\deoldify\visualize.py", line 425, in get_stable_image_colorizer
        learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
      File "F:\sd\extensions\sd-webui-deoldify\deoldify\generators.py", line 19, in gen_inference_wide
        learn.load(weights_name)
      File "F:\sd\extensions\sd-webui-deoldify\fastai\basic_train.py", line 267, in load
        if purge: self.purge(clear_opt=ifnone(with_opt, False))
      File "F:\sd\extensions\sd-webui-deoldify\fastai\basic_train.py", line 325, in purge
        for a in attrs_pkl: setattr(self, a, state[a])
    TypeError: 'NoneType' object is not subscriptable

**Comment by SpenserCai** [comment]
because deoldify will generate a zero-time file when inferring, and I will try to solve this problem so that there is no need to add unsafe parameters.

**Comment by lavalava45** [comment]
Hello again! After yesterday's update of SD the problem was gone by itself. So let's close the ticket.

**Comment by orbenda83** [comment]
The problem is still here. I have it now.

**Comment by croper-cpu** [comment]
The problem is still here.
