### ISSUE TITLE
Error when trying to generate

### ISSUE THREAD

**Issue by HenrysCat** [SpenserCai/sd-webui-deoldify#7]
Installed in Automatic1111 version: v1.5.1  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: ec41bd2a82
and get the error below after clicking generate.

TypeError: 'NoneType' object is not subscriptable

Then this in console

`*** Error verifying pickled file from C:\Users\user\stable-diffusion-webui\models\deoldify\tmpmv1m3lcr
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "C:\Users\user\stable-diffusion-webui\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "C:\Users\user\stable-diffusion-webui\modules\safe.py", line 95, in check_pt
        unpickler.load()
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1529, in load_global
        klass = self.find_class(module, name)
      File "C:\Users\user\stable-diffusion-webui\modules\safe.py", line 64, in find_class
        raise Exception(f"global '{module}/{name}' is forbidden")
    Exception: global 'functools/partial' is forbidden

---
*** Error completing request
*** Arguments: (0, <PIL.Image.Image image mode=RGB size=1502x1502 at 0x2DA2E5F43A0>, None, '', '', True, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, True, 35, False) {}
    Traceback (most recent call last):
      File "C:\Users\user\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\user\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\Users\user\stable-diffusion-webui\modules\postprocessing.py", line 62, in run_postprocessing
        scripts.scripts_postproc.run(pp, args)
      File "C:\Users\user\stable-diffusion-webui\modules\scripts_postprocessing.py", line 130, in run
        script.process(pp, **process_args)
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 54, in process
        pp.image = self.process_image(pp.image, render_factor, artistic)
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 46, in process_image
        vis = get_image_colorizer(root_folder=Path(paths_internal.models_path),render_factor=render_factor, artistic=artistic)
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 416, in get_image_colorizer
        return get_stable_image_colorizer(root_folder=root_folder, render_factor=render_factor)
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 425, in get_stable_image_colorizer
        learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\generators.py", line 19, in gen_inference_wide
        learn.load(weights_name)
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-deoldify\fastai\basic_train.py", line 267, in load
        if purge: self.purge(clear_opt=ifnone(with_opt, False))
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-deoldify\fastai\basic_train.py", line 325, in purge
        for a in attrs_pkl: setattr(self, a, state[a])
    TypeError: 'NoneType' object is not subscriptable

---
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
`

**Comment by SpenserCai** [comment]
you need add --disable-safe-unpickle in start command
