### ISSUE TITLE
Error on install 

### ISSUE THREAD

**Issue by VeteranXT** [SpenserCai/sd-webui-deoldify#72]
````
venv "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
ROCm Toolkit 5.7 was found.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 2e4a9d6f849294b4f2988d8e7f93bf10259e52cb
Using ZLUDA in E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\.zluda
Installing requirements
All models for DeOldify are already downloaded.
Installing fastai==1.0.60 for DeOldify extension.
Installing fastai
Installing yt-dlp for DeOldify extension.
Installing yt-dlp
Launching Web UI with arguments: --zluda --no-half --attention-quad

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\launch.py", line 54, in <module>
    main()
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\launch.py", line 50, in main
    start()
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 648, in start
    import webui
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\webui.py", line 17, in <module>
    initialize_forge()
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules_forge\initialization.py", line 58, in initialize_forge
    from backend import memory_management
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 10, in <module>
    from backend import stream, utils
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\backend\stream.py", line 59, in <module>
    current_stream = get_current_stream()
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\backend\stream.py", line 21, in get_current_stream
    torch.zeros((1, 1)).to(device, torch.float32)
E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\backend\stream.py:21: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  torch.zeros((1, 1)).to(device, torch.float32)
Total VRAM 8176 MB, total RAM 32679 MB
pytorch version: 2.3.1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6600 XT [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using sub quadratic optimization for cross attention
Using split attention for VAE
ONNX failed to initialize: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\launch.py", line 54, in <module>
    main()
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\launch.py", line 50, in main
    start()
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 648, in start
    import webui
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\webui.py", line 19, in <module>
    initialize.imports()
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\initialize.py", line 32, in imports
    from modules import processing, gradio_extensions, ui  # noqa: F401
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\modules\processing.py", line 15, in <module>
    from skimage import exposure
  File "E:\Storage\Apps\AI_Geneartor\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\skimage\__init__.py", line 122, in <module>
    from ._shared import geometry
  File "geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Press any key to continue . . .
````

After i did install it throws this error after i did apply/refresh,  and crashes after trying to start stable diffusion.

**Comment by IKsares** [comment]
Same here

      `venv "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\Scripts\Python.exe"
      fatal: detected dubious ownership in repository at 'C:/Users/Ignacio Casares/Downloads/stable-diffusion-webui'
      'C:/Users/Ignacio Casares/Downloads/stable-diffusion-webui' is owned by:
              BUILTIN/Administradores (S-1-5-32-544)
      but the current user is:
              DESKTOP-3CUSL5N/Ignacio Casares (S-1-5-21-2564267680-1505559237-2203032433-1001)
      To add an exception for this directory, call:
      
              git config --global --add safe.directory 'C:/Users/Ignacio Casares/Downloads/stable-diffusion-webui'
      fatal: detected dubious ownership in repository at 'C:/Users/Ignacio Casares/Downloads/stable-diffusion-webui'
      'C:/Users/Ignacio Casares/Downloads/stable-diffusion-webui' is owned by:
              BUILTIN/Administradores (S-1-5-32-544)
      but the current user is:
              DESKTOP-3CUSL5N/Ignacio Casares (S-1-5-21-2564267680-1505559237-2203032433-1001)
      To add an exception for this directory, call:
      
              git config --global --add safe.directory 'C:/Users/Ignacio Casares/Downloads/stable-diffusion-webui'
      Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
      Version: 1.10.1
      Commit hash: <none>
      Installing requirements
      All models for DeOldify are already downloaded.
      Installing fastai==1.0.60 for DeOldify extension.
      Installing fastai
      Launching Web UI with arguments:
      
      A module that was compiled using NumPy 1.x cannot be run in
      NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
      versions of NumPy, modules must be compiled with NumPy 2.0.
      Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
      
      If you are a user of the module, the easiest solution will be to
      downgrade to 'numpy<2' or try to upgrade the affected module.
      We expect that some modules will need time to support NumPy 2.
      
      Traceback (most recent call last):  File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\launch.py", line 48, in <module>
          main()
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\launch.py", line 44, in main
          start()
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\modules\launch_utils.py", line 465, in start
          import webui
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\webui.py", line 13, in <module>
          initialize.imports()
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\modules\initialize.py", line 15, in imports
          import torch  # noqa: F401
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\__init__.py", line 1382, in <module>
          from .functional import *  # noqa: F403
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\functional.py", line 7, in <module>
          import torch.nn.functional as F
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
          from .modules import *  # noqa: F403
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\__init__.py", line 35, in <module>
          from .transformer import TransformerEncoder, TransformerDecoder, \
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\transformer.py", line 20, in <module>
          device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
        warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
      no module 'xformers'. Processing without...
      no module 'xformers'. Processing without...
      No module 'xformers'. Proceeding without it.
      Traceback (most recent call last):
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\launch.py", line 48, in <module>
          main()
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\launch.py", line 44, in main
          start()
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\modules\launch_utils.py", line 465, in start
          import webui
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\webui.py", line 13, in <module>
          initialize.imports()
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\modules\initialize.py", line 39, in imports
          from modules import processing, gradio_extensons, ui  # noqa: F401
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\modules\processing.py", line 15, in <module>
          from skimage import exposure
        File "C:\Users\Ignacio Casares\Downloads\stable-diffusion-webui\venv\lib\site-packages\skimage\__init__.py", line 122, in <module>
          from ._shared import geometry
        File "geometry.pyx", line 1, in init skimage._shared.geometry
      ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
      Presione una tecla para continuar . . .`

**Comment by Archviz360** [comment]
same here 

    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (C:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\pydantic\fields.py)

**Comment by retikulumx** [comment]
The error message is not a bunch of funny letters making party, if you're able to read you be able to fix this yourself:

The error message tells you exactly what's going on:
> 'C:/Users/Ignacio Casares/Downloads/stable-diffusion-webui' is owned by:
>           BUILTIN/Administradores (S-1-5-32-544)
>   but the current user is:
>           DESKTOP-3CUSL5N/Ignacio Casares (S-1-5-21-2564267680-1505559237-2203032433-1001)

And how to fix it
>To add an exception for this directory, call:  
>        git config --global --add safe.directory 'C:/Users/Ignacio Casares/Downloads/stable-diffusion-webui'

You could also just change the ownership of your folder to your current user (non-Admin). Easy.
