### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Tobe2d** [SpenserCai/sd-webui-deoldify#8]
When I was testing it on an BW image I got errors as follow:

In the ui the error:
```
TypeError: 'NoneType' object is not subscriptable
Time taken: 6.2 sec.

A: 3.56 GB, R: 3.56 GB, Sys: 6.2/23.9883 GB (25.9%)
```

and from the log error:

```
*** Error completing request
*** Arguments: (0, <PIL.Image.Image image mode=RGB size=976x549 at 0x200521FEA10>, None, '', '', True, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, True, 35, False) {}
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "E:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "E:\stable-diffusion-webui\modules\postprocessing.py", line 62, in run_postprocessing
        scripts.scripts_postproc.run(pp, args)
      File "E:\stable-diffusion-webui\modules\scripts_postprocessing.py", line 130, in run
        script.process(pp, **process_args)
      File "E:\stable-diffusion-webui\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 54, in process
        pp.image = self.process_image(pp.image, render_factor, artistic)
      File "E:\stable-diffusion-webui\extensions\sd-webui-deoldify\scripts\postprocessing_deoldify.py", line 46, in process_image
        vis = get_image_colorizer(root_folder=Path(paths_internal.models_path),render_factor=render_factor, artistic=artistic)
      File "E:\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 416, in get_image_colorizer
        return get_stable_image_colorizer(root_folder=root_folder, render_factor=render_factor)
      File "E:\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\visualize.py", line 425, in get_stable_image_colorizer
        learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
      File "E:\stable-diffusion-webui\extensions\sd-webui-deoldify\deoldify\generators.py", line 19, in gen_inference_wide
        learn.load(weights_name)
      File "E:\stable-diffusion-webui\extensions\sd-webui-deoldify\fastai\basic_train.py", line 267, in load
        if purge: self.purge(clear_opt=ifnone(with_opt, False))
      File "E:\stable-diffusion-webui\extensions\sd-webui-deoldify\fastai\basic_train.py", line 325, in purge
        for a in attrs_pkl: setattr(self, a, state[a])
    TypeError: 'NoneType' object is not subscriptable

---
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
```

**Comment by SpenserCai** [comment]
you need add start command

**Comment by SpenserCai** [comment]
[#6](https://github.com/SpenserCai/sd-webui-deoldify/issues/6)
